[package]
org = "devantdemos"
name = "salesforce_lead_conversion_notification_to_slack"
version = "0.1.0"
title = "salesforce-lead-conversion-notification-to-slack"
distribution = "2201.13.1"

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "8.3.0"
